kind: pipeline
type: docker
name: default

steps:
  - name: "Install and Build"
    image: node:lts-buster
    commands:
      - yarn install --frozen-lockfile
      - yarn next:build
    environment:
      NEXT_PUBLIC_API_URL:
        from_secret: NEXT_PUBLIC_API_URL
      NEXT_PUBLIC_APIKEY:
        from_secret: NEXT_PUBLIC_APIKEY

  - name: "Release"
    image: node:lts-buster
    commands:
      - yarn semantic-release
    depends_on:
      - Install and Build
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    when:
      branch:
        include:
          - main
trigger:
  event:
    exclude:
      - tag
      - promote
