kind: pipeline
type: docker
name: default

steps:
  - name: "Install and Build"
    image: node:lts-buster
    commands:
      - yarn install --frozen-lockfile
      - yarn build
    environment:
      NEXT_PUBLIC_API_URL:
        from_secret: NEXT_PUBLIC_API_URL
      NEXT_PUBLIC_APIKEY:
        from_secret: NEXT_PUBLIC_APIKEY

  - name: "Docker build latest"
    image: plugins/docker
    settings:
      repo: stiforr/notes-frontend
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_APIKEY
    environment:
      NEXT_PUBLIC_API_URL:
        from_secret: NEXT_PUBLIC_API_URL
      NEXT_PUBLIC_APIKEY:
        from_secret: NEXT_PUBLIC_APIKEY

  - name: "Release"
    image: node:lts-buster
    commands:
      - yarn semantic-release
    depends_on:
      - "Install and Build"
      - "Docker build latest"
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    when:
      branch:
        include:
          - main
          - develop

  - name: Helm Package
    image: stiforr/ci-tools:1
    pull: 'always'
    commands:
      - helm package chart/
    when:
      event:
        include:
          - tag

  - name: Helm Push
    image: stiforr/ci-tools:1
    pull: 'always'
    commands:
      - /scripts/helm-push.sh
    depends_on:
      - 'Helm Package'
    environment:
      CHART_REPO_NAME:
        from_secret: CHART_REPO_NAME
      HELM_REPO_USERNAME:
        from_secret: HELM_REPO_USERNAME
      HELM_REPO_PASSWORD:
        from_secret: HELM_REPO_PASSWORD
      CHART_REPO_URL: https://harbor.k8s.stiforr.tech/chartrepo/stiforr

trigger:
  branch:
    exclude:
      - renovate/*