version: 2.1
jobs:
  build_install:
    docker:
      - image: "circleci/node:14"
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: build
          command: yarn next:build
workflows:
  build_install:
    jobs:
      - build_install
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test
